version: "3.5"

services:
  api-storage:
    build:
      context: .
      dockerfile: ./docker/api-storage/Dockerfile
    image: api-storage
    container_name: api-storage
    ports:
      - "9000:9000"
      - "80:80"
    volumes:
      # - ./api-storage:/var/www/html
      # - ./upload:/var/www/html/public/upload
      - ./storage.sqlite:$DB_DATABASE
    env_file:
      - .env
    command: php -S 0.0.0.0:9000 -t public

